spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailytest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8090


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mwy.demo.entity

upload-file:
  #对应项目所在的根目录
 fileUrl: /static/image/

